# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_name', models.CharField(max_length=200)),
                ('cars_model', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_name', models.CharField(max_length=200)),
                ('details_price', models.IntegerField()),
                ('details_isav', models.BooleanField(default=False)),
                ('details_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cars')),
            ],
            options={
                'db_table': 'details',
            },
        ),
    ]
