# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('is_checked', models.BooleanField(default=False)),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cars')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Details')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
