# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma', '0003_forma_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma',
            name='problem',
            field=models.TextField(default='', max_length=200),
        ),
    ]
