# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forma', '0004_auto_20151212_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forma',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='forma',
            old_name='name',
            new_name='username',
        ),
    ]
