# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forma', '0005_auto_20151212_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forma',
            old_name='username',
            new_name='user_name',
        ),
    ]
